name: wheelchair_monitor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  share_plus: ^10.1.2
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/wheeling_forward.png
    - assets/images/wheeling_forward1.png    
    - assets/images/wheeling_forward2.png
    - assets/images/wheeling_forward3.png
    - assets/images/wheeling_backward1.png    
    - assets/images/wheeling_backward2.png
    - assets/images/wheeling_backward3.png
    - assets/images/wheeling_on_spot.png
    - assets/icons/logo.png


flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/logo.png
